// <auto-generated />
using CIS174CourseWebsite.Areas.M5T4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CIS174CourseWebsite.Migrations.Student
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CIS174CourseWebsite.Areas.M5T4.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Albert",
                            Grade = "A",
                            LastName = "Einstein"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Dwayne",
                            Grade = "C-",
                            LastName = "Dibbley"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Alfred E.",
                            Grade = "F",
                            LastName = "Neuman"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "Rubin",
                            Grade = "B",
                            LastName = "Farr"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
